#!/bin/bash
# shellcheck disable=SC1090
# Mini file downloader and logger for filewebx
# Should be named '_' in the same directory as the filewebx script
# VERSION 2.1.0
# source: 'https://github.com/ColasNahaboo/filewebx'
################################# Filewebdl, filewebx downloader

nl=$'\n';  tab=$'\t'           # some useful constants
configfile='../filewebx.conf'
[[ -e "$configfile" ]] && . "$configfile"

declare -Ag metas
notfound(){                     # Return 404 Header
    echo "Status: 404 Not Found${nl}Content-Type: text/plain$nl"
    echo "404 File Not Found: $1"
    exit 1
}

# url/_/pass/filename or url/_/~guestid/pass/filename
# (with the filename part ignored: can be omitted or made human-friendly)
if [[ $PATH_INFO =~ ^((/[~][[:alnum:]]+)?/([[:alnum:]]+))/ ]]; then
    meta=../data"${BASH_REMATCH[1]}".meta
    gid="${BASH_REMATCH[2]}"
    pass="${BASH_REMATCH[3]}"
    [[ -e "$meta" ]] || notfound "(no meta) $gid$pass"
    . "$meta"                   # read metadatas into "metas"
    filename="${metas[name]}"
    file="${meta%.*},$filename"
    [[ -e "$file" ]] || notfound "(no file) $filename"
    # log only if the url was for a valid and active file:
    log="${meta%.meta}".log
    size=$(stat -c %s "$file")
    date=$(date --iso=seconds -u)
    clienthost=$(host "$REMOTE_ADDR" | grep -oP 'domain name pointer +\K.*' | head -n 1)
    echo "$date${tab}$REMOTE_ADDR${tab}${clienthost%.}${tab}$HTTP_USER_AGENT" >>"$log"
    qname="${filename//\\/\\\\}"
    qname="${qname//\"/\\\"}"
    echo "Content-Type: application/octet-stream"
    echo "Content-Disposition: attachment; filename=\"$qname\""
    echo "Content-Length: $size$nl"
    cat "$file"
else
    notfound "(bad url) ${PATH_INFO##*/}"
fi

exit 0
