# A sample config for the INSTALL script
# copy into .ul.conf or give it as argument to INSTALL
# The name of the ul script once installed.
# Use only alphanumeric chars. Make it unguessable! This is the only protection.
name=aiV6shujahla4ei
# Where to copy it by rsync: e.g. user@server/path/to/cgi
dest=user@my.server.com:/var/www/files/cgi-bin
# The URL of the dest dir above
url=https://my.server.com/cgi-bin
