# Virtual Host Settings
docRoot                   /www/filewebx/data
vhDomain                  filewebx.mysite.com

# Headers (via rewrite or context)
context / {
  location                /www/filewebx/data
  allowBrowse             0
  addHeader               Referrer-Policy no-referrer
}

# CGI Context
context /cgi {
  type                    cgi
  location                /www/filewebx/cgi
}

# Rewrite Rules (Admin Redirects)
rewrite  {
  enable                  1
  RewriteCond %{REMOTE_ADDR} ^88\.181\.8\.140$ [OR]
  RewriteCond %{REMOTE_ADDR} ^32\.166\.24\.45$
  RewriteRule ^(/|/cgi/|/cgi/ul)$ /cgi/aiV6shujahla4ei [R=301,L]
}

errorlog /var/log/ols/filewebx_error.log {
  useServer               0
  logLevel                DEBUG
}
